using System;
using System.Collections.Generic;

namespace Kreta.Core;

/// <summary>
/// General-purpose, flexible entity for persisting ANY new feature (e.g. notice board / NoticeMessage,
/// event calendar, voting, message wall, etc.).
///
/// PURPOSE: In the self-evolving system, the user can request hundreds of new, unknown features.
/// It is not realistic for a developer (Claude) to manually add a new C# domain class and new
/// Context method for every single new concept - that is NO LONGER self-evolution, but traditional development.
///
/// Instead, the code generated by Gemini uses this SINGLE, already existing entity and the
/// QueryEntities / GetEntity / SaveEntity / DeleteEntity methods available on the Contexts,
/// with a self-chosen `EntityType` label (e.g. "NoticeMessage") and arbitrary key-value data in the `Data` field.
/// This way Gemini can TRULY INDEPENDENTLY create brand-new features without recompilation.
/// </summary>
public class GenericRecord
{
    public int Id { get; set; }

    /// <summary>
    /// A freely chosen label by the AI identifying the feature (e.g. "NoticeMessage", "Event", "Vote").
    /// Every instance of the same feature uses the same EntityType value.
    /// </summary>
    public string EntityType { get; set; } = string.Empty;

    /// <summary>
    /// In which role the record was created (for audit / RBAC purposes).
    /// </summary>
    public Role CreatedByRole { get; set; }

    /// <summary>
    /// The identifier of the user who created/last modified it (optional).
    /// </summary>
    public int? CreatedByUserId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// Arbitrary key-value data (e.g. "Title" -> "Sports day cancelled", "Text" -> "...",
    /// "TargetClass" -> "9.A"). Stored as JSON in the database.
    /// </summary>
    public Dictionary<string, string> Data { get; set; } = new();
}