using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Kreta.Services.AI;

/// <summary>
///     DTO containing the result of the conformance check between the generated C# code and the formal specification.
/// </summary>
public class PromptConformanceResult
{
    /// <summary>
    ///     True if the code conforms 100% to the specification (neither under- nor over-generation).
    /// </summary>
    public bool IsStrictlyConformant { get; set; }

    /// <summary>
    ///     Coverage rate of the mandatorily requested methods (0.0 - 1.0, i.e. 0% - 100%).
    /// </summary>
    public double CoverageRate { get; set; }

    /// <summary>
    ///     Number of detected unauthorized, forbidden, or over-generated calls (Scope Creep Count).
    /// </summary>
    public int ScopeCreepCount { get; set; }

    /// <summary>
    ///     List of mandatory methods missing from the code but prescribed by the specification.
    /// </summary>
    public List<string> MissingRequiredMethods { get; set; } = new();

    /// <summary>
    ///     List of forbidden or over-generated method calls detected in the code.
    /// </summary>
    public List<string> DetectedForbiddenCalls { get; set; } = new();

    /// <summary>
    ///     List of all method calls identified in the code for auditing.
    /// </summary>
    public List<string> IdentifiedMethodCalls { get; set; } = new();

    /// <summary>
    ///     Detailed validation log messages for TDK measurements.
    /// </summary>
    public List<string> ValidationLogs { get; set; } = new();

    /// <summary>
    ///     Textual summary of the verification result.
    /// </summary>
    public string Summary => IsStrictlyConformant
        ? $"[CONFORMANCE SUCCESS] 100%-os konformitás! Lefedettség: {CoverageRate * 100:F0}%, Mellékhatások: {ScopeCreepCount}."
        : $"[CONFORMANCE FAILURE] Eltérés a specifikációtól! Lefedettség: {CoverageRate * 100:F0}%, Hiányzó: {MissingRequiredMethods.Count}, Tiltott/Extra: {ScopeCreepCount}.";
}

/// <summary>
///     Interface for the Prompt-to-Code Conformance verification service.
/// </summary>
public interface IPromptConformanceVerifier
{
    /// <summary>
    ///     Compares the generated C# source code with the formal specification, checking for under- and over-generation.
    /// </summary>
    /// <param name="csharpSource">The C# code generated by AI.</param>
    /// <param name="spec">The specification produced by the Formal Prompt Refiner.</param>
    /// <returns>Detailed results of the validation check.</returns>
    PromptConformanceResult VerifyConformance(string csharpSource, FormalPromptSpecification spec);
}

/// <summary>
///     Roslyn AST (Abstract Syntax Tree) based verification engine that guarantees
///     that the generated code does neither more nor less than requested.
/// </summary>
public class PromptConformanceVerifier : IPromptConformanceVerifier
{
    public PromptConformanceResult VerifyConformance(string csharpSource, FormalPromptSpecification spec)
    {
        var result = new PromptConformanceResult();

        if (string.IsNullOrWhiteSpace(csharpSource))
        {
            result.ValidationLogs.Add("A megadott C# forráskód üres.");
            result.IsStrictlyConformant = false;
            return result;
        }

        try
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(csharpSource);
            var root = syntaxTree.GetRoot();

            var invocationNodes = root.DescendantNodes().OfType<InvocationExpressionSyntax>();
            var identifiedCalls = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var invocation in invocationNodes)
            {
                var callText = invocation.Expression.ToString();

                if (callText.Contains(".")) callText = callText.Split('.').Last();

                identifiedCalls.Add(callText);
            }

            result.IdentifiedMethodCalls = identifiedCalls.ToList();
            result.ValidationLogs.Add($"Aknázott metódushívások az AST-ban: {string.Join(", ", identifiedCalls)}");


            var requiredCount = spec.RequiredContextMethods?.Count ?? 0;
            var matchedRequiredCount = 0;

            if (spec.RequiredContextMethods != null && requiredCount > 0)
            {
                foreach (var reqMethod in spec.RequiredContextMethods)
                {
                    var cleanReqName = reqMethod.Replace("()", "").Trim();

                    var isPresent = identifiedCalls.Any(call =>
                        call.Equals(cleanReqName, StringComparison.OrdinalIgnoreCase));
                    if (isPresent)
                    {
                        matchedRequiredCount++;
                    }
                    else
                    {
                        result.MissingRequiredMethods.Add(cleanReqName);
                        result.ValidationLogs.Add($"[ALULGENERÁLÁS] Hiányzó kötelező metódus: '{cleanReqName}'");
                    }
                }

                result.CoverageRate = (double)matchedRequiredCount / requiredCount;
            }
            else
            {
                result.CoverageRate = 1.0;
            }

            if (spec.ForbiddenContextMethods != null)
                foreach (var forbiddenMethod in spec.ForbiddenContextMethods)
                {
                    var cleanForbiddenName = forbiddenMethod.Replace("()", "").Trim();

                    var isDetected = identifiedCalls.Any(call =>
                        call.Equals(cleanForbiddenName, StringComparison.OrdinalIgnoreCase));
                    if (isDetected)
                    {
                        result.DetectedForbiddenCalls.Add(cleanForbiddenName);
                        result.ValidationLogs.Add(
                            $"[TÚLGENERÁLÁS / TILTOTT HÍVÁS] Megengedhetetlen metódushívás észlelve: '{cleanForbiddenName}'");
                    }
                }

            if (spec.TargetRole.Equals("Student", StringComparison.OrdinalIgnoreCase))
            {
                var studentForbiddenList = new[]
                {
                    "AddGrade", "CreateUser", "DeleteUser", "AssignClassToStudent", "AddLesson", "SaveEntity",
                    "DeleteEntity"
                };
                foreach (var forbidden in studentForbiddenList)
                    if (identifiedCalls.Contains(forbidden) && !result.DetectedForbiddenCalls.Contains(forbidden))
                    {
                        result.DetectedForbiddenCalls.Add(forbidden);
                        result.ValidationLogs.Add(
                            $"[RBAC SÉRÉS] Diák szerepkörben tiltott hívás található: '{forbidden}'");
                    }
            }

            result.ScopeCreepCount = result.DetectedForbiddenCalls.Count;

            result.IsStrictlyConformant = result.MissingRequiredMethods.Count == 0 && result.ScopeCreepCount == 0;

            Console.WriteLine("=========================================");
            Console.WriteLine("[PromptConformanceVerifier] EREDMÉNY:");
            Console.WriteLine($" - {result.Summary}");
            Console.WriteLine("=========================================");

            return result;
        }
        catch (Exception ex)
        {
            result.ValidationLogs.Add($"AST elemezési hiba történt: {ex.Message}");
            result.IsStrictlyConformant = false;
            return result;
        }
    }
}